#!/bin/bash

# ----------------------------- Add Default Flags ---------------------------- #
alias df='df -h'
alias ftp='ftp -i'
alias grep='grep --color' # Mark up the matching text with the expression stored in GREP_COLOR environment variable.
alias ls='ls -FA'         # make ls more useful (file type markers, everything but . and .. etc.)
alias ping="ping -c5"
alias scp='scp -C'        # Compression enable.  Passes the -C flag to ssh(1) to enable compression.

# --------------------------------- shorthand -------------------------------- #
alias dnow='sudo shutdown -h now; exit' # shutdown the machine now
alias fgrep='grep -F'                   # Interpret pattern as a set of fixed strings
alias gs="git status"                   # create a simple git status alias
alias h=history                         # shorthand for history
alias mkPatch='diff -Naur'
alias showpid='ps ${SHOWPIDFLAGS:--auxl} | head -1 >&2; ps ${SHOWPIDFLAGS:--auxl} | grep -v grep | grep -i'
alias showenv='env | grep -i'
alias vi=vim                            # redirect vi to vim.

# ------------------------------------ Misc ---------------------------------- #
alias vim='mvim -v'                    # use macvim in the terminal

# shellcheck disable=SC2139
alias Ping="$(which ping)"             # an alias to a ping that won't end
alias safari='~/bin/new_safari_window' # open urls in a new safari window


alias zshconfig="subl ~/.zshrc"
alias zshconfiglocal="subl ~/.zprofile.local"

# shellcheck disable=SC2139,SC2154
alias edconfig="subl $config"
alias edwork="subl $work/*.sublime-project"