#!/bin/bash

SWD=$(pwd) # cash the staring working directory
cd ${BASH_SOURCE%/*} || exit

. colors

# ==================================================================================================================== #
#                                                   Install Homebrew                                                   #
# -------------------------------------------------------------------------------------------------------------------- #
#                                         The missing package manager for OS X                                         #
# ==================================================================================================================== #

#------------------------------------------------- Check for Homebrew --------------------------------------------------
if test ! "$(type brew)"; then
	# Install if we don't have it
	format green "Installing Hombrew---------------------------------------------------------------------------------------"
	# Redirect stdin to /dev/null so that it won't ask if you are sure. This is
	# a hack and based on undocumented digging into the source so it may break
	# and need to be updated
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
fi

#---------------------------------------- Install miscellaneous brew utilities -----------------------------------------
format green "Installing other brew utilities -------------------------------------------------------------------------"

apps=(
	cmake                   #  A family of tools designed to build, test and package software.
	coreutils               #  adds color to ls
	docker
	docker-compose
	fontconfig              #  A library for configuring and customizing font access.
	freetype                #  A freely available software library to render fonts.
	git                     #  the backbone of all version control
	imagemagick             #  Use to create, edit, compose, or convert bitmap images.
	openssl                 #  provides a robust, commercial-grade, and full-featured toolkit for the TLS and SSL protocols.
	p7zip                   #  utility for opening zip64 files.
	potrace                 #  A tool for tracing a bitmap.
	python                  #  better then system python
	python3                 #  Not icluded with the system.
	shellcheck              #  linter for shell scripts
	terminal-notifier       #  Send User Notifications on Mac OS X 10.8 from the command-line.
	the_silver_searcher     #  A code-searching tool similar to ack, but faster... Much Faster.
	tmux                    #  A terminal multiplexer
	tree                    #  A recursive directory listing command that produces a depth indented listing of files.
	ttf2eot                 #  Convert TTF to EOT
	wget                    #  A free software package for retrieving files using HTTP, HTTPS and FTP
	zsh-syntax-highlighting #  Fish shell like syntax highlighting for Zsh.
)

brew install "${apps[@]}"
brew cleanup

trap 'cd $SWD' EXIT

# vim:tabstop=4:shiftwidth=4
