#!/bin/bash

SWD=$(pwd) # cash the staring working directory
cd "${BASH_SOURCE%/*}" || exit

. colors

# Install Hombrew Cask
format green "Installing Hombrew Cask----------------------------------------------------------------------------------"
brew tap caskroom/cask

brew cleanup

# ------------------------------------------- Add the needed taps for cask ---------------------------------------------
brew tap caskroom/fonts    # Adds fonts
brew tap caskroom/versions # Adds versions

# Apps
apps=(
	# ------------------------------------------------------ Fonts -----------------------------------------------------
	font-fontawesome      # Font Awesome gives you scalable vector icons that can instantly be customized
	font-monoid-nerd-font # Monoid + Powerline, Font Awesome, Octicons, Devicons, and other icon fonts.

	# ---------------------------------------------------- Quicklook ---------------------------------------------------
	provisionql         # iOS & OSX profiles
	qlcolorcode         # source code with syntax highlighting
	qlimagesize         # display dimensions/size of images in title bar and preview unsupported formats like WebP & bpg.
	qlmarkdown          # Markdown files.
	qlprettypatch       # patch files.
	qlstephen           # plain text files without a file extension
	qlvideo             # shows static previews, cover art and metadata for most types of video files.
	suspicious-package  # OS X Installer Packages

	# ------------------------------------------------------- Misc -----------------------------------------------------
	alfred             # much better than spotlight (checkout the workflows)
	appcleaner         # A small application which allows you to thoroughly uninstall unwanted apps.
	bettertouchtool    # configure many gestures for your Magic Mouse, Macbook Trackpad and Magic Trackpad
	docker             # provides the docker gui
	insomnia           # Finally, a REST client you'll love! Debug APIs like a human, not a robot
	iterm2-nightly     # iTerm2 brings the terminal into the modern age with features you never knew you always wanted.
	joinme             # FREE - Robust remote screen sharing/confrencing
	macvim             # the macOS port of vim
	robo-3t            # Mongodb Gui
	rowanj-gitx        # my personal preference on gui git client
	slack              # Work Instant Messanger
	virtualbox         # VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product
)


# --------------------------------------------------- Remove apps ------------------------------------------------------
format green "Removing apps so that we don't get duplicates -----------------------------------------------------------"

cd /Applications || exit
rm -rf "${apps[@]}"

brew cask uninstall "${apps[@]}"

# --------------------------------------------------- Install apps -----------------------------------------------------
format green "Installing apps with Cask -------------------------------------------------------------------------------"
brew cask install "${apps[@]}"

# ------------------------------------------------------ Cleanup -------------------------------------------------------
format green "Cleaning up ---------------------------------------------------------------------------------------------"
brew cleanup

trap 'cd $SWD' EXIT

# vim:tabstop=4:shiftwidth=4
