#!/bin/bash

SWD=$(pwd) # cash the staring working directory
cd ${BASH_SOURCE%/*} || exit
cwd=$(pwd)

. colors

format green "Git global config ---------------------------------------------------------------------------------------"
git config --global user.name "Jonathan Baird"
git config --global user.email "jtbairdj@gmail.com"

trap 'cd $SWD' EXIT

# vim:tabstop=4:shiftwidth=4
