#!/bin/bash

SWD=$(pwd) # cash the staring working directory
cd "${BASH_SOURCE%/*}" || exit

. colors

format green "Git global config ---------------------------------------------------------------------------------------"
git config --global user.name "Jonathan Baird"
git config --global user.email "jtbairdsr@me.com"

trap 'cd $SWD' EXIT

# vim:tabstop=4:shiftwidth=4
