#!/bin/bash

#==============================================================================#
#                      INSTALL NODE AND ALL GLOBAL PACKAGES                    #
#==============================================================================#

echo "Installing NVM..........................................................."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
command -v nvm

echo "Installing Node.........................................................."
nvm install node

echo "Installing Ionic..."
npm insatll -g ionic

echo "Installing linters..."
npm install -g stylelint htmllint eslint tslint swaglint write-good csscomb tern

echo "Installing precompilers..."
npm install -g instant-markdown sass

echo "Installing Typescript..."
npm install -g typescript tslint

echo "Installing Misc CLIs..."
npm install -g @angular/cli yo

echo "Installing Servers..."
npm install -g light-server http-server
