#!/bin/bash

SWD=$(pwd) # cash the staring working directory
cd ${BASH_SOURCE%/*} || exit

. colors

# ==================================================================================================================== #
#                                         INSTALL NODE AND ALL GLOBAL PACKAGES                                         #
# ==================================================================================================================== #

format green "Installing NVM..........................................................................................."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
command -v nvm

export NVM_DIR="$HOME/.nvm"
# shellcheck source=$HOME/.nvm/nvm.sh
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# shellcheck source=$HOME/.nvm/nvm.sh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm use system
npm uninstall -g a_module

format green "Installing Node.........................................................................................."
nvm install node

npm config delete prefix


read -rp "Would you like to install gobal node modules? (Y/n): " yn
yn=${yn:-'Yes'}
case "$yn" in
	[Yy]* )
		format green "Installing Node Modules.................................................................................."
		modules=(
		# ------------------------------------------------------ ionic -----------------------------------------------------
		ionic
		# ----------------------------------------------------- linters ----------------------------------------------------
		stylelint
		htmllint
		eslint
		tslint
		swaglint
		write-good
		csscomb
		tern
		# --------------------------------------------------- precompilers -------------------------------------------------
		sass
		# ---------------------------------------------------- typescript --------------------------------------------------
		typescript
		tslint
		# ------------------------------------------------------- clis -----------------------------------------------------
		@angular/cli
		yo
		# ------------------------------------------------------ servers ---------------------------------------------------
		light-server
		http-server
		)

		npm install -g "${modules[@]}"
		;;
	* )
		format green "To install global modules use \`npm install -g <module>\`................................................"
		;;
esac

trap 'cd $SWD' EXIT

# vim:tabstop=4:shiftwidth=4

