#!/usr/bin/env bash

SWD=$(pwd) # cash the staring working directory
cd "${BASH_SOURCE%/*}" || exit

. colors

format green "Installing tmux build dependencies for a DEBIAN distro --------------------------------------------------"

sudo apt update

sudo apt install -y git

sudo apt install -y automake
sudo apt install -y build-essential
sudo apt install -y pkg-config
sudo apt install -y libevent-dev
sudo apt install -y libncurses5-dev

. ./tmux

trap 'cd $SWD' EXIT
